name: flutter_tutorial
description: Tutorial API to display overlay and highlights certain items.
version: 0.0.1
homepage: https://github.com/appunite/flutter_tutorial

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: